# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import python_service_pb2 as python__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in python_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonServiceStub(object):
    """Python服务接口定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSimeng = channel.unary_unary(
                '/com.traffic.sim.grpc.PythonService/CreateSimeng',
                request_serializer=python__service__pb2.CreateSimengRequest.SerializeToString,
                response_deserializer=python__service__pb2.ApiResponse.FromString,
                _registered_method=True)
        self.ControlGreenRatio = channel.unary_unary(
                '/com.traffic.sim.grpc.PythonService/ControlGreenRatio',
                request_serializer=python__service__pb2.GreenRatioControlRequest.SerializeToString,
                response_deserializer=python__service__pb2.ApiResponse.FromString,
                _registered_method=True)
        self.TestConnection = channel.unary_unary(
                '/com.traffic.sim.grpc.PythonService/TestConnection',
                request_serializer=python__service__pb2.Empty.SerializeToString,
                response_deserializer=python__service__pb2.TestResponse.FromString,
                _registered_method=True)


class PythonServiceServicer(object):
    """Python服务接口定义
    """

    def CreateSimeng(self, request, context):
        """初始化仿真引擎
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlGreenRatio(self, request, context):
        """绿信比控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestConnection(self, request, context):
        """测试连接
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSimeng': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSimeng,
                    request_deserializer=python__service__pb2.CreateSimengRequest.FromString,
                    response_serializer=python__service__pb2.ApiResponse.SerializeToString,
            ),
            'ControlGreenRatio': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlGreenRatio,
                    request_deserializer=python__service__pb2.GreenRatioControlRequest.FromString,
                    response_serializer=python__service__pb2.ApiResponse.SerializeToString,
            ),
            'TestConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.TestConnection,
                    request_deserializer=python__service__pb2.Empty.FromString,
                    response_serializer=python__service__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.traffic.sim.grpc.PythonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.traffic.sim.grpc.PythonService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonService(object):
    """Python服务接口定义
    """

    @staticmethod
    def CreateSimeng(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.traffic.sim.grpc.PythonService/CreateSimeng',
            python__service__pb2.CreateSimengRequest.SerializeToString,
            python__service__pb2.ApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlGreenRatio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.traffic.sim.grpc.PythonService/ControlGreenRatio',
            python__service__pb2.GreenRatioControlRequest.SerializeToString,
            python__service__pb2.ApiResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.traffic.sim.grpc.PythonService/TestConnection',
            python__service__pb2.Empty.SerializeToString,
            python__service__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
