# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'map_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11map_service.proto\x12\x1f\x63om.traffic.sim.plugin.map.grpc\"M\n\x11\x43onvertMapRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x91\x01\n\x12\x43onvertMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08xml_data\x18\x03 \x01(\x0c\x12\x15\n\rxml_file_name\x18\x04 \x01(\t\x12\x19\n\x11\x63onversion_method\x18\x05 \x01(\t\x12\x15\n\rxml_file_path\x18\x06 \x01(\t\"M\n\x11PreviewMapRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"|\n\x12PreviewMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0cpreview_data\x18\x03 \x01(\t\x12\x12\n\nroad_count\x18\x04 \x01(\x05\x12\x1a\n\x12intersection_count\x18\x05 \x01(\x05\x32\x81\x02\n\x11MapConvertService\x12u\n\nConvertMap\x12\x32.com.traffic.sim.plugin.map.grpc.ConvertMapRequest\x1a\x33.com.traffic.sim.plugin.map.grpc.ConvertMapResponse\x12u\n\nPreviewMap\x12\x32.com.traffic.sim.plugin.map.grpc.PreviewMapRequest\x1a\x33.com.traffic.sim.plugin.map.grpc.PreviewMapResponseB4\n\x1f\x63om.traffic.sim.plugin.map.grpcB\x0fMapServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.traffic.sim.plugin.map.grpcB\017MapServiceProtoP\001'
  _globals['_CONVERTMAPREQUEST']._serialized_start=54
  _globals['_CONVERTMAPREQUEST']._serialized_end=131
  _globals['_CONVERTMAPRESPONSE']._serialized_start=134
  _globals['_CONVERTMAPRESPONSE']._serialized_end=279
  _globals['_PREVIEWMAPREQUEST']._serialized_start=281
  _globals['_PREVIEWMAPREQUEST']._serialized_end=358
  _globals['_PREVIEWMAPRESPONSE']._serialized_start=360
  _globals['_PREVIEWMAPRESPONSE']._serialized_end=484
  _globals['_MAPCONVERTSERVICE']._serialized_start=487
  _globals['_MAPCONVERTSERVICE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
