# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import map_service_pb2 as map__service__pb2


class MapConvertServiceStub(object):
    """地图转换服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertMap = channel.unary_unary(
                '/com.traffic.sim.plugin.map.grpc.MapConvertService/ConvertMap',
                request_serializer=map__service__pb2.ConvertMapRequest.SerializeToString,
                response_deserializer=map__service__pb2.ConvertMapResponse.FromString,
                )
        self.PreviewMap = channel.unary_unary(
                '/com.traffic.sim.plugin.map.grpc.MapConvertService/PreviewMap',
                request_serializer=map__service__pb2.PreviewMapRequest.SerializeToString,
                response_deserializer=map__service__pb2.PreviewMapResponse.FromString,
                )


class MapConvertServiceServicer(object):
    """地图转换服务
    """

    def ConvertMap(self, request, context):
        """转换地图文件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewMap(self, request, context):
        """预览地图（简化转换，用于快速预览）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapConvertServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertMap': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertMap,
                    request_deserializer=map__service__pb2.ConvertMapRequest.FromString,
                    response_serializer=map__service__pb2.ConvertMapResponse.SerializeToString,
            ),
            'PreviewMap': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewMap,
                    request_deserializer=map__service__pb2.PreviewMapRequest.FromString,
                    response_serializer=map__service__pb2.PreviewMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.traffic.sim.plugin.map.grpc.MapConvertService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MapConvertService(object):
    """地图转换服务
    """

    @staticmethod
    def ConvertMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.traffic.sim.plugin.map.grpc.MapConvertService/ConvertMap',
            map__service__pb2.ConvertMapRequest.SerializeToString,
            map__service__pb2.ConvertMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PreviewMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.traffic.sim.plugin.map.grpc.MapConvertService/PreviewMap',
            map__service__pb2.PreviewMapRequest.SerializeToString,
            map__service__pb2.PreviewMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
